### ISSUE TITLE
Can't leave comment when hiding comments

### ISSUE THREAD

**Issue by xmo-odoo** [Mottie/GitHub-userscripts#122]
This extension got my interest because on some PRs with lots of inline comments traffic it can be difficult to even see the code inbetween the comments.

I wanted the ability to see the PR as if it were brand new, for clarity. However, when hiding comments the new comments are also hidden, making this idea impossible.

*Collapsing* comment allows writing new ones, but still leaves rather large gaps in the file, which are somewhat confusing as they look a lot like hunk changes (especially when using the Github Dark stylus theme, as the hunk header has a color scheme rather undifferentiated from the background itself, making it less differentiable than the blue/white of the default color scheme).

**Comment by Mottie** [comment]
Hi @xmo-odoo!

Sorry for not responding earlier. I just fixed a bunch of other stuff, but forgot about this issue. Sorry... it'll probably have to wait another week until I have more time to work on it.

**Comment by xmo-odoo** [comment]
@Mottie no worries, it's no worse than before I installed the userscript so it's hardly a life-and-death issue

**Comment by Mottie** [comment]
I haven't thoroughly tested this update, but it seems to be working as expected.

**Comment by xmo-odoo** [comment]
It seems to work fine when *collapsing* comments but not when *hiding* comments

[Here's a screencast](https://github.com/Mottie/GitHub-userscripts/files/5304604/Screencast.2020-09-30.11.50.00.mp4.tar.gz), as you can see when using "Collapse" the new comment box still appears, but when using "hide" it's not possible to open an editor.

Again my use case is a bit specific so I can understand if you decide not to support it: on some pull requests there are dozens of comments on the diff so it's very hard to read the code and leave comments as the diff is completely broken up by interspersed comments, so I wanted to fold the existing comments in order to get a "unified view" of the PR diff in order to have an easier time reading and commenting (then un-collapse and check if my comments were redundant with existing ones I guess).
